sycltest_EXTERNAL_DEPENDS := TBB SYCL
SYCLCore_DEPENDS := Framework
Test1_DEPENDS := Framework SYCLCore DataFormats
Test2_DEPENDS := Framework SYCLCore
BeamSpotProducer_DEPENDS := Framework SYCLCore DataFormats
SYCLDataFormats_DEPENDS := SYCLCore DataFormats
SiPixelClusterizer_DEPENDS := Framework SYCLCore SYCLDataFormats DataFormats
