sycl_EXTERNAL_DEPENDS := $(sycl_EXTERNAL_DEPENDS)
SYCLCore_DEPENDS := Framework
Test1_DEPENDS := Framework SYCLCore DataFormats
Test2_DEPENDS := Framework SYCLCore
BeamSpotProducer_DEPENDS := Framework SYCLCore DataFormats
SYCLDataFormats_DEPENDS := SYCLCore DataFormats
SiPixelClusterizer_DEPENDS := Framework SYCLCore SYCLDataFormats CondFormats DataFormats
CondFormats_DEPENDS := SYCLCore